
services:
- type: web
  name: flask-postgres-api
  env: python
  repo: https://github.com/Git-It-Done1/GitItDone_Rostering.git
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: flask-postgres-api-settings
  - key: FLASK_SQLALCHEMY_DATABASE_URI
    fromDatabase:
      name: flask-postgres-api-db
      property: connectionString 

envVarGroups:
- name: flask-postgres-api-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py
    

databases:
- name: flask-postgres-api-db
  plan: free
  databaseName: mydb
